//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 Color;
//   float ZeffMax;
//   float ZeffMin;
//   sampler2D ZeffTexture;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   ZeffMin      c0       1
//   ZeffMax      c1       1
//   Color        c2       1
//   ZeffTexture  s0       1
//

    ps_2_0
    def c3, -0, -1, 0, 0
    dcl t0.xy
    dcl_2d s0
    texld r0, t0, s0
    add r0.y, r0.x, -c1.x
    add r0.x, -r0.x, c0.x
    cmp r0.y, r0.y, c3.x, c3.y
    cmp r0.x, r0.x, c3.z, r0.y
    mov r0.z, c3.z
    cmp r0, r0.x, r0.z, c2
    mov oC0, r0

// approximately 8 instruction slots used (1 texture, 7 arithmetic)
